name: Update Core Blockchain

on:
  push:
    branches: [ main ]
    paths:
      - 'core/**'
      - 'api/**'
      - 'node/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f node/requirements.txt ]; then
            pip install -r node/requirements.txt
          fi
          
      - name: Create deployment package
        run: |
          mkdir -p deployment/core-updates
          cp -r core deployment/core-updates/
          cp -r api deployment/core-updates/
          cp -r node/routes deployment/core-updates/routes
          cd deployment
          zip -r core-updates.zip core-updates
          cd ..
      
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            # Create deployment directory
            mkdir -p ~/deployment
            cd ~/deployment
            
            # Download deployment packages
            curl -o core-updates.zip ${{ secrets.DOWNLOAD_URL }}/core-updates.zip
            
            # Backup current core files
            timestamp=$(date +%Y%m%d%H%M%S)
            mkdir -p ~/backups/$timestamp/core
            mkdir -p ~/backups/$timestamp/api
            mkdir -p ~/backups/$timestamp/routes
            
            # Backup from actual bootstrap node directories
            cp -r ~/bootstrap_node_1/core/* ~/backups/$timestamp/core/ || true
            cp -r ~/bootstrap_node_1/api/* ~/backups/$timestamp/api/ || true
            cp -r ~/bootstrap_node_1/routes/* ~/backups/$timestamp/routes/ || true
            
            # Extract updates
            unzip -o core-updates.zip
            
            # Make backup of blockchain data from bootstrap nodes
            mkdir -p ~/backups/$timestamp/blockchain_data
            cp -r ~/bootstrap_node_1/globalcoyn_blockchain_data.json ~/backups/$timestamp/blockchain_data/ || true
            cp -r ~/bootstrap_node_2/globalcoyn_blockchain_data.json ~/backups/$timestamp/blockchain_data/node2_data.json || true
            
            # Copy core updates to the actual bootstrap node directories
            echo "Deploying to bootstrap_node_1 and bootstrap_node_2 directories"
            
            # Ensure directories exist
            mkdir -p ~/bootstrap_node_1/core
            mkdir -p ~/bootstrap_node_2/core
            mkdir -p ~/bootstrap_node_1/api/routes
            mkdir -p ~/bootstrap_node_2/api/routes
            mkdir -p ~/bootstrap_node_1/routes
            mkdir -p ~/bootstrap_node_2/routes
            
            # Copy core files
            cp -r core-updates/core/* ~/bootstrap_node_1/core/ || true
            cp -r core-updates/core/* ~/bootstrap_node_2/core/ || true
            
            # Copy API routes
            cp -r core-updates/api/routes/* ~/bootstrap_node_1/api/routes/ || true
            cp -r core-updates/api/routes/* ~/bootstrap_node_2/api/routes/ || true
            
            # Copy node routes
            cp -r core-updates/routes/* ~/bootstrap_node_1/routes/ || true
            cp -r core-updates/routes/* ~/bootstrap_node_2/routes/ || true
            
            # Also update blockchain directory for reference
            mkdir -p /var/www/globalcoyn/blockchain/core
            mkdir -p /var/www/globalcoyn/blockchain/api/routes
            mkdir -p /var/www/globalcoyn/blockchain/node/routes
            cp -r core-updates/core/* /var/www/globalcoyn/blockchain/core/ || true
            cp -r core-updates/api/routes/* /var/www/globalcoyn/blockchain/api/routes/ || true
            cp -r core-updates/routes/* /var/www/globalcoyn/blockchain/node/routes/ || true
            
            # Clean up
            rm -rf core-updates
            rm core-updates.zip
            
            # Restart the bootstrap nodes to apply changes
            echo "Restarting bootstrap node services..."
            sudo systemctl restart globalcoyn-bootstrap1.service || true
            sudo systemctl restart globalcoyn-bootstrap2.service || true
            sudo systemctl restart globalcoyn-node.service || true
            
            echo "Core blockchain update completed at $(date)"